art/art/urls.py
from django.contrib import admin
from django.urls import path
from artapp import views
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('artapp/',include('artapp.urls')),
    path("logout/",views.user_logout,name='logout'),
    path("home1",views.home1,name="home1"),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

art/artapp/urls.py
from django.urls import path
from django.conf.urls import url
from artapp import views

app_name='artapp'

urlpatterns=[path("user_login/",views.user_login,name="user_login"),
path("register",views.register,name="register"),
path("profile",views.profile,name='profile'),
url(r'^artworks1/(?P<pk>[0-9]+)$', views.artworks1, name='artworks1'),
path("viewart/",views.viewart,name='viewart'),
path("viewall/",views.viewall,name='viewall'),
url(r'^more1/(?P<pk>[0-9]+)$', views.more1, name='more1'),
url(r'^more2/(?P<pk>[0-9]+)$', views.more22, name='more2'),
url(r'^details/(?P<pk>[0-9]+)$', views.details1, name='details'),
path('portfolio', views.portfolio, name='portfolio'),
]

art/artapp/models.py
from django.db import models
from django.contrib.auth.models import User


           
class artwork1(models.Model):
    user1=models.ForeignKey(User,on_delete=models.CASCADE)
    art=models.ImageField(upload_to='artworks',blank=True)   
    def __str__(self):
        return str(self.user1)
        
class more(models.Model):
    user1=models.OneToOneField(User,on_delete=models.CASCADE)
    ppic=models.ImageField(upload_to='profile_pics' ,blank=True)
    
    def __str__(self):
        return str(self.user1)
 
 
class more2(models.Model):
    user1=models.OneToOneField(User,on_delete=models.CASCADE)
    coverphoto=models.ImageField(upload_to='cover_pics' ,blank=True)
    
    def __str__(self):
        return str(self.user1)
        
        
class details(models.Model):
    user1=models.OneToOneField(User,on_delete=models.CASCADE)
    age=models.IntegerField(blank=False)
    Dob=models.DateField(blank=True,null=True)
    about=models.TextField(blank=True)
    link=models.URLField(blank=True)
    link1=models.URLField(blank=True)
    def __str__(self):
        return str(self.user1)
        
    

art/artapp/forms.py
from django import forms
from django.contrib.auth.models import User
from artapp.models import artwork1,more,more2,details

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('first_name','last_name','username','password','email')
        
class useredit(forms.ModelForm):
    class Meta():        
        model=User
        fields=('first_name','last_name','username',)
        
class artworkform1(forms.ModelForm):
    class Meta():
        model=artwork1
        fields=('art',) 

        
class moreform(forms.ModelForm):
    class Meta():
        model=more
        fields=('ppic',)
        
class moreform2(forms.ModelForm):
    class Meta():
        model=more2
        fields=('coverphoto',)
        
class detailsform(forms.ModelForm):
    class Meta():
        model=details
        fields=('age','Dob','about','link','link1',)
        

art/artapp/views.py
from django.shortcuts import render
from . import forms
from . import models
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from artapp.models import artwork1,more,more2,details
from artapp.forms import UserForm,artworkform1,moreform,moreform2,detailsform,useredit
from django.contrib.auth.models import User
from django.views.generic import UpdateView



def index(request):
    return render(request,'artapp/index.html')
    
     
def home1(request):
    return render(request,'artapp/home1.html')
    
    
    
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
    
def register(request):
    registered=False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        if user_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            
            registered=True
            return HttpResponse("<h1>you have been successfully registered</h1>")
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
        
    return render(request,'artapp/registration.html',{'user_form':user_form, 'register':register})
    
    
def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                
                return HttpResponseRedirect(reverse('home1'))
            else:
                return HttpResponse("Sorry! Account is not active")
        else:
            return HttpResponse("someone tried to login and failed!")
            
    else:
        return render(request,'artapp/login.html',{})
        
        
def profile(request):
    temp=details.objects.filter(user1=request.user)
    pic2=more2.objects.filter(user1=request.user)
    pic=more.objects.filter(user1=request.user)
    context={'user':request.user,'pic':pic,'pic2':pic2,'temp':temp}
    return render(request,'artapp/profile.html',context)
    
    
@login_required    
def portfolio(request):
    temp=details.objects.filter(user1=request.user)
    pic2=more2.objects.filter(user1=request.user)
    pic=more.objects.filter(user1=request.user)
    artwork=artwork1.objects.filter(user1=request.user)[:5]
    context={'user':request.user,'pic':pic,'pic2':pic2,'temp':temp,'artwork':artwork}
    
    return render(request,'artapp/portfolio.html',context)
    
    
@login_required   
def viewart(request):
    artwork=artwork1.objects.filter(user1=request.user)
    return render(request,'artapp/viewart.html',{'artwork':artwork})  
       

# Create your views here.
      
def artworks1(request,pk):
    if request.method=='POST':
        form=artworkform1(request.POST)
        if form.is_valid():
            us=User.objects.filter(is_superuser=False)
            form.instance.user1 = us.get(pk=pk)     
            artwork=form.save(commit=False)
                    
            if 'art' in request.FILES:
                artwork.art=request.FILES['art']
                artwork.save()
                return HttpResponseRedirect(reverse("home1"))
        else:
            return HttpResponse("<h2>Shit</h2>")
                
    else:
        form = artworkform1(pk)
                
    return render(request,'artapp/artworks1.html',{'user':request.user,'artwork_form':form})
    
    
    
    
@login_required 
def more1(request,pk):
        pic=more.objects.filter(user1=request.user)
        if request.user.id == int(pk):
        
            if request.method=='POST':
                
                form=moreform(request.POST)
                if form.is_valid():
                    
                    us=User.objects.filter(is_superuser=False)
                    form.instance.user1=us.get(pk=pk)
                    
                    profile=form.save(commit=False)
                    if 'ppic' in request.FILES:
                        more.objects.filter(user1=request.user).delete()
                        profile.ppic=request.FILES['ppic']
                        profile.save()
                        return HttpResponseRedirect(reverse('home1'))
                        
                else:
                    return HttpResponse("<h1>Shit</h1>")
            else:
                form=moreform(pk)
            return render(request,'artapp/more.html',{'user':request.user,'profile_form':form,'pic':pic})
            
           
@login_required 
def details1(request,pk):
    if request.user.id == int(pk):
        wf=forms.detailsform()
    
        if request.method=='POST':
            wf=detailsform(request.POST)
            if wf.is_valid():
                us=User.objects.filter(is_superuser=False)
                wf.instance.user1=us.get(pk=pk)
                details.objects.filter(user1=request.user).delete()
                wf.save()
            else:
                print("invalid data entered")
        else:
            wf=detailsform()
        return render(request,'artapp/details.html',{'wf':wf})
        
            
            
            
@login_required 
def more22(request,pk):
        pic2=more2.objects.filter(user1=request.user)
        if request.user.id == int(pk):
        
            if request.method=='POST':
                
                form2=moreform2(request.POST)
                if form2.is_valid():
                    
                    us=User.objects.filter(is_superuser=False)
                    form2.instance.user1=us.get(pk=pk)
                    
                    profile2=form2.save(commit=False)
                    if 'coverphoto' in request.FILES:
                        more2.objects.filter(user1=request.user).delete()
                        profile2.coverphoto=request.FILES['coverphoto']
                        profile2.save()
                        return HttpResponseRedirect(reverse('home1'))
                        
                else:
                    return HttpResponse("<h1>Shit</h1>")
            else:
                form2=moreform2(pk)
            return render(request,'artapp/more11.html',{'user':request.user,'cover_form':form2,'pic2':pic2})
 
def navbar(request,pk):
    pic=more.objects.filter(user1=request.user)
    return render(request,'artapp/base.html',{'pic':pic})
    

def viewall(request):
    artwork=artwork1.objects.all()
    return render(request,'artapp/viewall.html',{'artwork':artwork})
    
    
   

art/artapp/templates/artapp/artworks1.html
{% extends "artapp/base.html" %}
{%block body_block %}
<br><br>

<h2 class="h1" style="text-align:center">Artworks</h2><br>
<h4 class="h3"style="text-align:center">Upload here </h4>
<div class="reg1">
<form method='POST' enctype="multipart/form-data">
{%csrf_token%}
{{af.as_p}}
{{artwork_form.as_p}} 
<input type="submit" value="Upload">
</form>
</div>
{%endblock%}

art/artapp/templates/artapp/base.html
{%load static %}
<html>

<head><title></title> <link rel="stylesheet" href="{%static 'css/design.css'%}"> </head>
<body id="bg" style="background-image: url('{%static "images/d.jpg"%}')";>

<ul>

{% if pic %}
{% for i in pic%}
<a href="{%url 'artapp:more1' user.id%}">
<li>
<img style=" width:50px; height:50px; border-radius:50%; border:solid 3px grey; margin-right:-160px;" class="profile" src="{{i.ppic.url}}" alt="sorry" width=150px height=100px;/>
</a></li>
{%endfor%}
{%endif%}


{% if user.is_authenticated %}

<li style="margin:10px; margin-left: 110px;"><a href="{%url 'artapp:profile'%}">Profile</a></li>
<li style="margin:10px"><a href="{%url 'artapp:artworks1' user.id%}">Upload Art</a></li>
<li style="margin:10px"><a href="{%url 'artapp:viewart'%}">My Artworks</a></li>
<li style="margin:10px; margin-right:0px;"><a href="{%url 'artapp:portfolio'%}">Portfolio</a><li>
<li style="margin:10px"><a href="{%url 'artapp:viewall'%}">All Artworks</a></li>
<li style="margin:10px; margin-left:500px;"><a href="{%url 'logout'%}">Logout</a></li>


{%else%}
<li style="margin:10px"> <a href="{%url 'index'%}"> Homepage </a></li>
<li style="margin:10px"><a href="{%url 'artapp:user_login'%}">Login</a></li>
<li style="margin:10px"><a href="{%url 'admin:index'%}">Admin</a> </li>
<li style="margin:10px"><a href="{%url 'artapp:register'%}">Register</a></li>
<li style="margin:10px"><a href="{%url 'artapp:viewall'%}">All Artworks</a></li>
{%endif%}



</ul>
{% block body_block%}
{% endblock %}
</body>
</html>

art/artapp/templates/artapp/details.html
{%extends "artapp/base.html"%}
{%block body_block%}
<div class="h1">
<h1> More details </h1></div>

<div class="h3"><h3> Add Here</h3></div>
<div class="reg">
<br>
<form method='POST' enctype="multipart/form-data">
{%csrf_token%}

{{wf.as_p}}

<input type="submit" value="Save">
</form>
</div>
{%endblock%}

art/artapp/templates/artapp/home1.html
{% extends "artapp/base.html" %}
{%block body_block %}
<br><br>
<h1 class="h1" style="text-align:center">Home Page </h1><br> <br>
<h3 class="h3" style="text-align:center"></h3>

{%endblock%}

art/artapp/templates/artapp/index.html
{% extends "artapp/base.html" %}
{%block body_block %}
<br><br>
<h1 class="h3" style="text-align:center">Home Page </h1><br> <br>
<h3 class="h3" style="text-align:center">Here is the home page</h3>

{%endblock%}

art/artapp/templates/artapp/login.html
{%extends 'artapp/base.html'%}
{%block body_block%}

<h1 class="h1">Please Login</h1>
<div class="reg">
<form action="{%url 'artapp:user_login' %}" method="POST">

{%csrf_token%}

<p>Username : </p>
<input type="text" name="username" placeholder="enter username">

<p> Password : </p>
<input type="password" name="password">

<input type="submit" value="Login">
</form>
</div>
{%endblock%}

art/artapp/templates/artapp/more.html
{% extends "artapp/base.html" %}
{%block body_block %}
<br><br>
<h4 class="h3"style="text-align:center"></h4>
<div class="reg1" style="height:400px;opacity:1;" >

{% if pic %}
{% for i in pic%}
<img style="width:90%; height:90%; object-fit:contain;" class="profile" src="{{i.ppic.url}}" alt="sorry" width=150px height=100px;/>
{%endfor%}
{%endif%}

<div style="height:100px; opacity:0.75;  margin-left:30px; color:white;" class="reg2" >
<form method='POST' enctype="multipart/form-data">
{%csrf_token%}
{{profile_form.as_p}}
<div  style="opacity:1; margin-left:60px;">
<input type="submit" value="Change DP"></div>
</form></div>
</div>
{%endblock%}

art/artapp/templates/artapp/more11.html
{% extends "artapp/base.html" %}
{%block body_block %}
<br><br>
<h4 class="h3"style="text-align:center"></h4>
<div class="reg1" style="height:400px;opacity:1;" >

{% if pic2 %}
{% for i in pic2%}
<img style="width:90%; height:90%; object-fit:contain;" class="profile" src="{{i.coverphoto.url}}" alt="sorry" width=150px height=100px;/>
{%endfor%}
{%endif%}

<div style="height:100px; opacity:0.75;  margin-left:30px; color:white;" class="reg2" >
<form method='POST' enctype="multipart/form-data">
{%csrf_token%}
{{cover_form.as_p}}
<div  style="opacity:1; margin-left:60px;">
<input type="submit" value="Change Cover Photo"></div>
</form></div>
</div>
{%endblock%}

art/artapp/templates/artapp/portfolio.html
{% extends "artapp/base.html" %}
{%block body_block %}
<br><br> 
<div class="reg" style="height:1100px; width:1100px; margin-left:150px; background-color:grey; ">
{% if pic2 %}
{% for i in pic2%}
<div class="reg1" style="margin-left:35; margin-top:20px; height:250px;background-color:lightyellow; width:1000px;text-align:center ;opacity:0.8;">
<img style=" margin-top:10px; height:300px; width:950px; object-fit:contain; margin-left:30px; border-radius:5px; " class="profile" src="{{i.coverphoto.url}}" alt="sorry" width=150px height=100px;/>
</a>
{% if pic %}
{% for i in pic%}
<img style="margin-left:810px; height:150px; width:140px; object-fit:contain; border-radius:50%; border:solid 6px grey; margin-top:-250px; opacity:1;" class="profile" src="{{i.ppic.url}}" alt="sorry" width=150px height=100px;/>
</a>

{%endfor%}
{%endif%}

</div>
{%endfor%}
{%endif%}



<div class="reg1" style="margin-left:35;height:250px;background-color:lightblue; width:1000px;text-align:center; margin-top:-20;">
<p>Personal Details </p>
<p> Name       :{{user.first_name}} {{user.last_name}}</p><p> </p>
<p>email       :{{user.email}}</p>

{%if temp%}
{%for i in temp%}
{%if i.age%}
<p> Age : {{i.age}}</p>
{%endif%}
{%if i.Dob%} 
<p> Dob :  {{i.Dob}}</p>
{%endif%}
{%if i.about%}
</div>
<div class="reg1" style="margin-left:35; height:200px;background-color:lightyellow; width:1000px;text-align:center; margin-top:-40px ;opacity:0.8;">
<p> About :</p><p>  {{i.about}}</p></div>
{%endif%}

<div class="reg1" style="margin-left:35;height:150px;background-color:lightblue; width:1000px;text-align:center; margin-top:-20;">
{%if i.link%}
<p> Links to other profiles:</p>
<a href={{i.link}}>
<p style="font-size:14px;">{{i.link}}</p></a>
{%endif%}
{%if i.link1%} 
<a href={{i.link1}}>
<p style="font-size:14px;">{{i.link1}}</p></a>
{%endif%}
{%endfor%}
{%endif%}
</div>

<div class="reg1" style="margin-left:35; height:200px;background-color:lightyellow; width:1000px;text-align:center; margin-top:-30px ;opacity:0.8;">
{% if artwork %}
{%for i in artwork%}
<img src="{{i.art.url}}" alt="sorry" width=170px height=160px;/>{%endfor%}{%endif%}</div>



</div>
{%endblock%}

art/artapp/templates/artapp/profile.html
{% extends "artapp/base.html" %}
{%block body_block %}
<br><br>
<div class="reg" style="height:930px; width:1100px; margin-left:150px; background-color:grey;">
{% if pic2 %}
{% for i in pic2%}
<a href="{%url 'artapp:more2' user.id%}">
<img style=" margin-top:10px; height:300px; width:950px; object-fit:contain; margin-left:30px; border:solid 2px white; border-radius:5px; " class="profile" src="{{i.coverphoto.url}}" alt="sorry" width=150px height=100px;/>
</a>
{%endfor%}
{%endif%}
<div style="width:100px; height:20px; background-color:white; border-radius:10px; margin-top:-40px;">
<p><a href="{%url 'artapp:more2' user.id%}">Cover</a></p></div>
<div class="reg"  style="height:600px; margin-left:240px; margin-top:-30px;">

{% if pic %}
{% for i in pic%}
<a href="{%url 'artapp:more1' user.id%}">
<img style="margin-left:198px; height:150px; width:140px; object-fit:contain; border-radius:50%; border:solid 3px grey; margin-top:-90px; opacity:1;" class="profile" src="{{i.ppic.url}}" alt="sorry" width=150px height=100px;/>

</a>

{%endfor%}
{%endif%}

<a href="{%url 'artapp:more1' user.id%}"><p style= "margin-left:230px">Profile Pic</a></p>
<div class="reg1" style="margin-left:0px; height:170px;background-color:lightblue">
<a href="{%url 'artapp:details' user.id%}">Edit Details</a>
<p> First name       :{{user.first_name}}</p><p> Last name       :{{user.last_name}}</p>
<p> Username       :{{user}}</p>
<p>email       :{{user.email}}</p>
</div>
{%if temp%}
{%for i in temp%}
{%if i.age%}
<p> Age : {{i.age}}</p>
{%endif%}
{%if i.Dob%} 
<p> Dob :  {{i.Dob}}</p>
{%endif%}
{%if i.about%}
<p> About :  {{i.about}}</p>
{%endif%}
{%if i.link%}
<div class="reg1" style="margin-left:0px; height:120px;background-color:lightblue">
<p> Links to other profiles:</p>
<a href={{i.link}}>
<p style="font-size:14px;">{{i.link}}</p></a>
{%endif%}
{%if i.link1%} 
<a href={{i.link1}}>
<p style="font-size:14px;">{{i.link1}}</p></a>
{%endif%}
</div>
{%endfor%}
{%endif%}


</div></div>
{%endblock%}

art/artapp/templates/artapp/registration.html
{%extends "artapp/base.html"%}
{%block body_block%}
<div class="h1">
<h1> Registeration page </h1></div>
{% if registered %}
<h2> Thank You</h2>
{%else%}
<div class="h3"><h3> Register Here</h3></div>
<div class="reg">
<br>
<form method='POST' enctype="multipart/form-data">
{%csrf_token%}
{{user_form.as_p}}
{{profile_form.as_p}}
<input type="submit" value="Register">
</form>
</div>
{%endif%}
{%endblock%}

art/artapp/templates/artapp/user_update_form.html
{% extends "artapp/base.html" %}
{%block body_block %}
<br><br>

<h2 class="h1" style="text-align:center">Update Details</h2><br>
<h4 class="h3"style="text-align:center"></h4>
<div class="reg1">
<form method='POST' enctype="multipart/form-data">
{%csrf_token%}
{{user_form.as_p}}
<input type="submit" value="Upload">
</form>
</div>
{%endblock%}

art/artapp/templates/artapp/viewall.html
{% extends "artapp/base.html" %}
{%block body_block %}
<br><br>
<h1 class="h1" style="text-align:center; ">All Artworks Uploaded Yet </h1>
<h4 class="h3" style="text-align:center;">sorted datewise (newest at bottom)</h4>
<div class="reg2" style="background-color:grey; opacity:0.9;">
{% if artwork %}
{%for i in artwork%}
<img class="no_hover" src="{{i.art.url}}" alt="sorry" width=150px height=100px;/>
@{{i.user1}}
{%endfor%}{%endif%}</div>
{%endblock%}

art/artapp/templates/artapp/viewart.html
{% extends "artapp/base.html" %}
{%block body_block %}
<br><br>
<h1 class="h1" style="text-align:center">My Arts </h1>
<h4 class="h3" style="text-align:center">(click any image to go to profile)</h1>
<div class="reg2">
{% if artwork %}
{%for i in artwork%}
<a href="{%url 'artapp:profile'%}"><img src="{{i.art.url}}" alt="sorry" width=150px height=100px;/>{%endfor%}{%endif%}</div>
{%endblock%}